# Generated by Django 4.2.24 on 2025-09-24 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='reportfile',
            name='file',
            field=models.FileField(upload_to='report_files/'),
        ),
    ]
